/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weiersyuan_useffmpeg_AudioActivity */

#ifndef _Included_com_weiersyuan_useffmpeg_AudioActivity
#define _Included_com_weiersyuan_useffmpeg_AudioActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weiersyuan_useffmpeg_AudioActivity
 * Method:    render
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_weiersyuan_useffmpeg_AudioActivity_render
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
