/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weiersyuan_useffmpeg_MainActivity */

#ifndef _Included_com_weiersyuan_useffmpeg_MainActivity
#define _Included_com_weiersyuan_useffmpeg_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weiersyuan_useffmpeg_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_weiersyuan_useffmpeg_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
