/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weiersyuan_useffmpeg_FFmpegGraphrcsActivity */

#ifndef _Included_com_weiersyuan_useffmpeg_FFmpegGraphrcsActivity
#define _Included_com_weiersyuan_useffmpeg_FFmpegGraphrcsActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weiersyuan_useffmpeg_FFmpegGraphrcsActivity
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_weiersyuan_useffmpeg_VideoActivity_render
  (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_weiersyuan_useffmpeg_VideoActivity_stop
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
